version: "3.8"

services:
  db:
    image: postgres:9.6.18-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - "127.0.0.1:8090:8080"
